services:
  db:
    container_name: postgres-db
    image: postgres:17.2
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: zeroday
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

  smtp4dev:
    container_name: smtp4dev
    image: rnwood/smtp4dev:3.6.1
    restart: always
    ports:
      - "8082:80"
      - "25:25"

volumes:
  postgres-data: